' Batch Process Template
' Generated by SolidWorks MCP Server
' Operation: {{operation}}

Sub BatchProcess()
    Dim swApp As SldWorks.SldWorks
    Dim swModel As SldWorks.ModelDoc2
    Dim swFrame As SldWorks.Frame
    Dim vFiles As Variant
    Dim i As Integer
    Dim sFile As String
    Dim lErrors As Long
    Dim lWarnings As Long
    
    Set swApp = Application.SldWorks
    Set swFrame = swApp.Frame
    
    ' Get files matching pattern
    vFiles = swFrame.GetFiles("{{filePattern}}")
    
    If IsEmpty(vFiles) Then
        MsgBox "No files found matching pattern: {{filePattern}}"
        Exit Sub
    End If
    
    ' Process each file
    For i = 0 To UBound(vFiles)
        sFile = vFiles(i)
        
        ' Open file
        Set swModel = swApp.OpenDoc6(sFile, GetDocType(sFile), _
            swOpenDocOptions_Silent, "", lErrors, lWarnings)
        
        If Not swModel Is Nothing Then
            ' Perform operation
            {{#if (eq operation "export")}}
            ' Export to {{outputFormat}}
            Dim sNewPath As String
            sNewPath = Left(sFile, InStrRev(sFile, ".") - 1) & ".{{outputFormat}}"
            swModel.SaveAs3 sNewPath, 0, 0
            {{/if}}
            
            {{#if (eq operation "update_property")}}
            ' Update custom property
            Dim swCustPropMgr As SldWorks.CustomPropertyManager
            Set swCustPropMgr = swModel.Extension.CustomPropertyManager("")
            swCustPropMgr.Add3 "{{propertyName}}", _
                swCustomInfoType_e.swCustomInfoText, _
                "{{propertyValue}}", _
                swCustomPropertyAddOption_e.swCustomPropertyReplaceValue
            swModel.Save3 swSaveAsOptions_Silent, lErrors, lWarnings
            {{/if}}
            
            {{#if (eq operation "rebuild")}}
            ' Rebuild model
            swModel.ForceRebuild3 False
            swModel.Save3 swSaveAsOptions_Silent, lErrors, lWarnings
            {{/if}}
            
            {{#if (eq operation "print")}}
            ' Print to default printer
            swModel.PrintOut3 "", "", 1, False, "", False, False
            {{/if}}
            
            ' Close file
            swApp.CloseDoc swModel.GetTitle
        End If
    Next i
    
    MsgBox "Batch process complete. Processed " & (UBound(vFiles) + 1) & " files."
End Sub

Function GetDocType(sFile As String) As Long
    Dim sExt As String
    sExt = LCase(Right(sFile, 6))
    
    If InStr(sExt, "sldprt") > 0 Then
        GetDocType = swDocPART
    ElseIf InStr(sExt, "sldasm") > 0 Then
        GetDocType = swDocASSEMBLY
    ElseIf InStr(sExt, "slddrw") > 0 Then
        GetDocType = swDocDRAWING
    Else
        GetDocType = swDocNONE
    End If
End Function