' Modify Dimensions Template
' Generated by SolidWorks MCP Server

Sub ModifyDimensions()
    Dim swApp As SldWorks.SldWorks
    Dim swModel As SldWorks.ModelDoc2
    Dim swDim As SldWorks.Dimension
    Dim vDimensions As Variant
    Dim i As Integer
    
    Set swApp = Application.SldWorks
    Set swModel = swApp.ActiveDoc
    
    If swModel Is Nothing Then
        MsgBox "No active model"
        Exit Sub
    End If
    
    {{#each dimensions}}
    ' Modify dimension: {{this.name}}
    Set swDim = swModel.Parameter("{{this.name}}")
    If Not swDim Is Nothing Then
        swDim.SystemValue = {{this.value}} / 1000 ' Convert mm to m
        Debug.Print "Updated {{this.name}} to {{this.value}} mm"
    Else
        Debug.Print "Dimension {{this.name}} not found"
    End If
    {{/each}}
    
    ' Rebuild model
    swModel.EditRebuild3
    swModel.ViewZoomtofit2
    
    MsgBox "Updated {{dimensions.length}} dimension(s)"
End Sub